apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: google-photo-clone
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SMThapa/google-photo-clone.git
    targetRevision: main
    path: k8s-main/overlay/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: siddharth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true