apiVersion: kustomize.toolkit.fluxcd.io/v2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/google-photo-clone/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure   # ensures ArgoCD is installed before this applies